version: '3.8'

services:
  app:
    container_name: crudbooks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - mongodb
    volumes:
      - ./bin/:/root/
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017

  mongodb:
    image: mongo:latest
    container_name: mongoDB
