version: '3.8'

services:
  app:
    container_name: crudbooks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - SERVER_PORT=4001
      - GOFILE_SERVICE_API_KEY=GOFILE_SERVICE_API_KEY
      - GOFILE_FOLDER_TOKEN=GOFILE_FOLDER_TOKEN
      - DB_NAME=crudbooks
      - DB_LOGIN=admin
      - DB_PWD=0000
      - JWT_SECRET=JWT_SECRET
      - ACCESS_TOKEN_TTL=10m
      - REFRESH_TOKEN_TTL=24h

  mongodb:
    image: mongo:latest
    container_name: mongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
