version: '3.8'

services:
  app:
    container_name: crudbooks
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - mongodb
    volumes:
      - ./bin/:/root/
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017

  mongodb:
    image: mongo:latest
    container_name: mongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=0000
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
