version: '3.8'

services:
  app:
    image: 6576c36a34bb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./bin/:/root/

  mongodb:
    image: mongo:latest
    container_name: 58042414fbaa
    ports:
      - 27018:27017
